### ISSUE TITLE
'entity-type-mapping' not found

### ISSUE THREAD

**Issue by tabergma** [RasaHQ/tutorial-knowledge-base#5]
Hi @tabergma

I am having an issue with 'entity-type-mapping' too.
When I run rasa shell it gives me this error.

```
Your input -> hi Hi. I can give you some information about banks or I can give you some details about the accounts you own. What do you want to know? Your input -> i need my account details 2019-08-19 17:04:11 ERROR rasa.core.processor - Encountered an exception while running action 'action_query_attribute'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
```

and in the action server the following error pops up.

```
Traceback (most recent call last):
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 156, in send
response = next(self._response_iterator)
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 364, in next
return self._next()
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 358, in _next
raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "GraqlSemanticException-label 'entity-type-mapping' not found. Please check server logs for the stack trace."
debug_error_string = "{"created":"@1566214503.269706022","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"GraqlSemanticException-label 'entity-type-mapping' not found. Please check server logs for the stack trace.","grpc_status":3}"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functionsrule.endpoint
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
resp = make_response(f(*args, **kwargs))
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/endpoint.py", line 59, in webhook
response = executor.run(action_call)
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/executor.py", line 245, in run
events = action(dispatcher, tracker, domain)
File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/actions.py", line 245, in run
entity_type = get_entity_type(tracker)
File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/actions.py", line 44, in get_entity_type
return graph_database.map("entity-type-mapping", entity_type)
File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/graph_database.py", line 313, in map
f"match "
File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/graph_database.py", line 82, in _execute_attribute_query
result_iter = tx.query(query)
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 131, in query
return self._tx_service.query(query, infer)
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 49, in query
response = self._communicator.send(request)
File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 160, in send
raise GraknError("Server/network error: {0}\n\n generated from request: {1}".format(e, request))
grakn.exception.GraknError.GraknError: Server/network error: <_Rendezvous of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "GraqlSemanticException-label 'entity-type-mapping' not found. Please check server logs for the stack trace."
debug_error_string = "{"created":"@1566214503.269706022","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"GraqlSemanticException-label 'entity-type-mapping' not found. Please check server logs for the stack trace.","grpc_status":3}"

generated from request: query_req {
query: "match $mapping isa entity-type-mapping, has mapping-key 'None', has mapping-value $v;get $v;"
}

127.0.0.1 - - [2019-08-19 17:05:03] "POST /webhook HTTP/1.1" 500 411 0.226519
```

Glad if could you help me with this error.
I am using python 3.7
rasa 1.1.4
grakn 1.5.7

And i did not do any changes in actions.py or graph_database.py or any other file in the repository.

**Comment by tabergma** [comment]
@durashi Did you create the graph database? If yes, did you check if all needed data is in the database? You can use the UI of grakn (https://grakn.ai/grakn-kgms) to see how the schema looks and what data is in the database.

**Comment by durashi** [comment]
hello @tabergma,
I have cloned the repository again, cleaned grakn server and create the database add add data again. Here is what it looks like.

add schema.

```(RasaEnv) durashi@durashi-PC:~/grakn-core-all-linux-1.5.7$ ./grakn console --keyspace banking --file tutorial-knowledge-base/knowledge_base/schema.gql
Loading: tutorial-knowledge-base/knowledge_base/schema.gql
...
{}
Successful commit: schema.gql
```

add data.

```(RasaEnv) durashi@durashi-PC:~/grakn-core-all-linux-1.5.7/tutorial-knowledge-base$ python knowledge_base/migrate.py
Loading from [./knowledge_base/data/person] into Grakn ...
Inserted 20 items from [./knowledge_base/data/person] into Grakn.
Loading from [./knowledge_base/data/account] into Grakn ...
Inserted 26 items from [./knowledge_base/data/account] into Grakn.
Loading from [./knowledge_base/data/bank] into Grakn ...
Inserted 7 items from [./knowledge_base/data/bank] into Grakn.
Loading from [./knowledge_base/data/card] into Grakn ...
Inserted 26 items from [./knowledge_base/data/card] into Grakn.
Loading from [./knowledge_base/data/attribute_mapping] into Grakn ...
Inserted 46 items from [./knowledge_base/data/attribute_mapping] into Grakn.
Loading from [./knowledge_base/data/mention_mapping] into Grakn ...
Inserted 13 items from [./knowledge_base/data/mention_mapping] into Grakn.
Loading from [./knowledge_base/data/entity_type_mapping] into Grakn ...
Inserted 13 items from [./knowledge_base/data/entity_type_mapping] into Grakn.
Loading from [./knowledge_base/data/represented-by] into Grakn ...
Inserted 26 items from [./knowledge_base/data/represented-by] into Grakn.
Loading from [./knowledge_base/data/transaction] into Grakn ...
Inserted 2000 items from [./knowledge_base/data/transaction] into Grakn.
Loading from [./knowledge_base/data/contract] into Grakn ...
Inserted 26 items from [./knowledge_base/data/contract] into Grakn.
```

and then trained the model and run the rasa shell. It gives the same error.

```Your input ->  what are the last transactions
2019-08-20 16:41:16 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_query_entities'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
```

In the action server gives the following error again.

```Traceback (most recent call last):
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 156, in send
    response = next(self._response_iterator)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "GraqlSemanticException-label 'entity_type_mapping' not found. Please check server logs for the stack trace."
	debug_error_string = "{"created":"@1566299476.597585949","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"GraqlSemanticException-label 'entity_type_mapping' not found. Please check server logs for the stack trace.","grpc_status":3}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/endpoint.py", line 59, in webhook
    response = executor.run(action_call)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/executor.py", line 245, in run
    events = action(dispatcher, tracker, domain)
  File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/actions.py", line 162, in run
    entity_type = get_entity_type(tracker)
  File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/actions.py", line 44, in get_entity_type
    return graph_database.map("entity_type_mapping", entity_type)
  File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/graph_database.py", line 313, in map
    f"match "
  File "/home/durashi/grakn-core-all-linux-1.5.7/chatbot/graph_database.py", line 82, in _execute_attribute_query
    result_iter = tx.query(query)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 131, in query
    return self._tx_service.query(query, infer)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 49, in query
    response = self._communicator.send(request)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/service/Session/TransactionService.py", line 160, in send
    raise GraknError("Server/network error: {0}\n\n generated from request: {1}".format(e, request))
grakn.exception.GraknError.GraknError: Server/network error: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "GraqlSemanticException-label 'entity_type_mapping' not found. Please check server logs for the stack trace."
	debug_error_string = "{"created":"@1566299476.597585949","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"GraqlSemanticException-label 'entity_type_mapping' not found. Please check server logs for the stack trace.","grpc_status":3}"
>

 generated from request: query_req {
  query: "match $mapping isa entity_type_mapping, has mapping-key \'transactions\', has mapping-value $v;get $v;"
}

127.0.0.1 - - [2019-08-20 16:41:16] "POST /webhook HTTP/1.1" 500 411 0.224630
```

I am new to Rasa and I do not know whether i am doing anything wrong in here.

**Comment by durashi** [comment]
hello @tabergma,
I have cloned the repository again, cleaned grakn server and create the database add add data again. Here is what it looks like.

add schema.
```
Loading: tutorial-knowledge-base/knowledge_base/schema.gql
...
{}
Successful commit: schema.gql
```

add data.

```Loading from [./knowledge_base/data/person] into Grakn ...
Inserted 20 items from [./knowledge_base/data/person] into Grakn.
Loading from [./knowledge_base/data/account] into Grakn ...
Inserted 26 items from [./knowledge_base/data/account] into Grakn.
Loading from [./knowledge_base/data/bank] into Grakn ...
Inserted 7 items from [./knowledge_base/data/bank] into Grakn.
Loading from [./knowledge_base/data/card] into Grakn ...
Inserted 26 items from [./knowledge_base/data/card] into Grakn.
Loading from [./knowledge_base/data/attribute_mapping] into Grakn ...
Inserted 46 items from [./knowledge_base/data/attribute_mapping] into Grakn.
Loading from [./knowledge_base/data/mention_mapping] into Grakn ...
Inserted 13 items from [./knowledge_base/data/mention_mapping] into Grakn.
Loading from [./knowledge_base/data/entity_type_mapping] into Grakn ...
Inserted 13 items from [./knowledge_base/data/entity_type_mapping] into Grakn.
Loading from [./knowledge_base/data/represented-by] into Grakn ...
Inserted 26 items from [./knowledge_base/data/represented-by] into Grakn.
Loading from [./knowledge_base/data/transaction] into Grakn ...
Inserted 2000 items from [./knowledge_base/data/transaction] into Grakn.
Loading from [./knowledge_base/data/contract] into Grakn ...
Inserted 26 items from [./knowledge_base/data/contract] into Grakn.
```

and then trained the model and run the rasa shell. It gives the same error.

```2019-08-20 16:41:16 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_query_entities'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
```

In the action server gives the following error again.

````Traceback (most recent call last):
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 63, in __init__
    open_session_response = self._stub.open(RequestBuilder.open_session(keyspace, self.credentials))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1566304721.384963278","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1566304721.384960947","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1566304721.384941232","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":689,"grpc_status":14,"referenced_errors":[{"created":"@1566304721.384876514","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":205,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:48555"}]}]}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/endpoint.py", line 59, in webhook
    response = executor.run(action_call)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/executor.py", line 245, in run
    events = action(dispatcher, tracker, domain)
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/actions.py", line 162, in run
    entity_type = get_entity_type(tracker)
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/actions.py", line 44, in get_entity_type
    return graph_database.map("entity-type-mapping", entity_type)
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/graph_database.py", line 313, in map
    f"match "
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/graph_database.py", line 79, in _execute_attribute_query
    with client.session(keyspace=self.keyspace) as session:
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 23, in session
    return Session(self.uri, keyspace, self._channel, self.credentials)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 66, in __init__
    raise GraknError('Could not obtain sessionId for keyspace "{0}", stems from: {1}'.format(keyspace, e))
grakn.exception.GraknError.GraknError: Could not obtain sessionId for keyspace "banking", stems from: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1566304721.384963278","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1566304721.384960947","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1566304721.384941232","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":689,"grpc_status":14,"referenced_errors":[{"created":"@1566304721.384876514","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":205,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:48555"}]}]}]}"
>
127.0.0.1 - - [2019-08-20 18:08:41] "POST /webhook HTTP/1.1" 500 411 0.011362
```

I am new to Rasa and I do not know whether i am doing anything wrong in here.

**Comment by durashi** [comment]
hello @tabergma,
I have cloned the repository again, cleaned grakn server and create the database add add data again. Here is what it looks like.

add schema.

```
Loading: tutorial-knowledge-base/knowledge_base/schema.gql
...
{}
Successful commit: schema.gql
```

add data.

```
Loading from [./knowledge_base/data/person] into Grakn ...
Inserted 20 items from [./knowledge_base/data/person] into Grakn.
Loading from [./knowledge_base/data/account] into Grakn ...
Inserted 26 items from [./knowledge_base/data/account] into Grakn.
Loading from [./knowledge_base/data/bank] into Grakn ...
Inserted 7 items from [./knowledge_base/data/bank] into Grakn.
Loading from [./knowledge_base/data/card] into Grakn ...
Inserted 26 items from [./knowledge_base/data/card] into Grakn.
Loading from [./knowledge_base/data/attribute_mapping] into Grakn ...
Inserted 46 items from [./knowledge_base/data/attribute_mapping] into Grakn.
Loading from [./knowledge_base/data/mention_mapping] into Grakn ...
Inserted 13 items from [./knowledge_base/data/mention_mapping] into Grakn.
Loading from [./knowledge_base/data/entity_type_mapping] into Grakn ...
Inserted 13 items from [./knowledge_base/data/entity_type_mapping] into Grakn.
Loading from [./knowledge_base/data/represented-by] into Grakn ...
Inserted 26 items from [./knowledge_base/data/represented-by] into Grakn.
Loading from [./knowledge_base/data/transaction] into Grakn ...
Inserted 2000 items from [./knowledge_base/data/transaction] into Grakn.
Loading from [./knowledge_base/data/contract] into Grakn ...
Inserted 26 items from [./knowledge_base/data/contract] into Grakn.
```

and then trained the model and run the rasa shell. It gives the same error.

```
2019-08-20 16:41:16 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_query_entities'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
```

In the action server gives the following error again.

```Traceback (most recent call last):
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 63, in __init__
    open_session_response = self._stub.open(RequestBuilder.open_session(keyspace, self.credentials))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1566304721.384963278","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1566304721.384960947","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1566304721.384941232","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":689,"grpc_status":14,"referenced_errors":[{"created":"@1566304721.384876514","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":205,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:48555"}]}]}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/endpoint.py", line 59, in webhook
    response = executor.run(action_call)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/rasa_sdk/executor.py", line 245, in run
    events = action(dispatcher, tracker, domain)
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/actions.py", line 162, in run
    entity_type = get_entity_type(tracker)
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/actions.py", line 44, in get_entity_type
    return graph_database.map("entity-type-mapping", entity_type)
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/graph_database.py", line 313, in map
    f"match "
  File "/home/durashi/grakn-core-all-linux-1.5.7/tutorial-knowledge-base/graph_database.py", line 79, in _execute_attribute_query
    with client.session(keyspace=self.keyspace) as session:
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 23, in session
    return Session(self.uri, keyspace, self._channel, self.credentials)
  File "/home/durashi/python-virtual-environments/RasaEnv/lib/python3.7/site-packages/grakn/client.py", line 66, in __init__
    raise GraknError('Could not obtain sessionId for keyspace "{0}", stems from: {1}'.format(keyspace, e))
grakn.exception.GraknError.GraknError: Could not obtain sessionId for keyspace "banking", stems from: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1566304721.384963278","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1566304721.384960947","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1566304721.384941232","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":689,"grpc_status":14,"referenced_errors":[{"created":"@1566304721.384876514","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":205,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:48555"}]}]}]}"
>
127.0.0.1 - - [2019-08-20 18:08:41] "POST /webhook HTTP/1.1" 500 411 0.011362
```

I am new to Rasa and I do not know whether i am doing anything wrong in here.

**Comment by tabergma** [comment]
mmhh... seems like your database is set up correctly. Not sure why the mapping is not found. Can you please execute
```
grakn console --keyspace banking
```
and then query for the `entity-type-mapping`
```
match $x isa entity-type-mapping; get $x;
```
What is the result? If that is working, can your please check if you started your database on the correct port and if you used the `banking` keyspace?

**Comment by durashi** [comment]
hello @tabergma 
this is the result in grakn workbase,

![Screenshot from 2019-08-21 17-03-54](https://user-images.githubusercontent.com/43062937/63428665-b75ac200-c435-11e9-95e3-9d36c7421dbc.png)

**Comment by durashi** [comment]
Hi @tabergma,
There were no errors when i use sudo privileges. I guess I am having issue in installing in virtualenv. Now it is working without errors. Thank you very much for the support and quick replies. It is a good tutorial!

**Comment by durashi** [comment]
Hi @tabergma ,
There were no errors when i use sudo privileges. I guess I am having issue in installing in virtualenv. Now it is working without errors. Thank you very much for the support and quick replies. It is a good tutorial!

**Comment by tabergma** [comment]
Thanks! Glad it works now 🚀
